openapi: 3.0.1
info:
  version: 3.0.4
  title: Valhalla Config Definition
  contact:
    name: Valhalla
    url: "https://github.com/valhalla/valhalla"
components:
  schemas:
    logging:
      type: object
      properties:
        color:
          type: boolean
          default: true
        file_name:
          type: string
          default: path_to_some_file.log
        type:
          type: string
          default: std_out
    valhalla_config:
      type: object
      properties:
        additional_data:
          $ref: "#/components/schemas/additional_data"
        httpd:
          $ref: "#/components/schemas/httpd"
        loki:
          $ref: "#/components/schemas/loki"
        meili:
          $ref: "#/components/schemas/meili"
        mjolnir:
          $ref: "#/components/schemas/mjolnir"
        odin:
          $ref: "#/components/schemas/odin"
        service_limits:
          $ref: "#/components/schemas/service_limits"
        statsd:
          $ref: "#/components/schemas/statsd"
        thor:
          $ref: "#/components/schemas/thor"
    additional_data:
      type: object
      properties:
        elevation:
          type: string
          default: /custom_files/elevation_data
    httpd:
      type: object
      properties:
        service:
          type: object
          properties:
            drain_seconds:
              type: integer
              default: 28
            interrupt:
              type: string
              default: ipc:///tmp/interrupt
            listen:
              type: string
              default: tcp://*:8002
            loopback:
              type: string
              default: ipc:///tmp/loopback
            shutdown_seconds:
              type: integer
              default: 1
    loki:
      type: object
      properties:
        actions:
          type: array
          items:
            type: string
          default:
            [
              "locate",
              "route",
              "height",
              "sources_to_targets",
              "optimized_route",
              "isochrone",
              "trace_route",
              "trace_attributes",
              "transit_available",
              "expansion",
              "centroid",
              "status",
            ]
        logging:
          type: object
          properties:
            color:
              type: boolean
              default: true
            file_name:
              type: string
              default: path_to_some_file.log
            long_request:
              type: integer
              default: 100
            type:
              type: string
              default: std_out
        service:
          type: object
          properties:
            proxy:
              type: string
              default: ipc:///tmp/loki
        service_defaults:
          type: object
          properties:
            heading_tolerance:
              type: integer
              default: 60
            minimum_reachability:
              type: integer
              default: 50
            node_snap_tolerance:
              type: integer
              default: 5
            radius:
              type: integer
              default: 0
            search_cutoff:
              type: integer
              default: 35000
            street_side_max_distance:
              type: integer
              default: 1000
            street_side_tolerance:
              type: integer
              default: 5
        use_connectivity:
          type: boolean
          default: true
    meili:
      type: object
      properties:
        auto:
          type: object
          properties:
            search_radius:
              type: integer
              default: 50
            turn_penalty_factor:
              type: integer
              default: 200
        bicycle:
          type: object
          properties:
            turn_penalty_factor:
              type: integer
              default: 140
        customizable:
          type: array
          items:
            type: string
          default:
            [
              "mode",
              "search_radius",
              "turn_penalty_factor",
              "gps_accuracy",
              "interpolation_distance",
              "sigma_z",
              "beta",
              "max_route_distance_factor",
              "max_route_time_factor",
            ]
        default:
          type: object
          properties:
            beta:
              type: integer
              default: 3
            breakage_distance:
              type: integer
              default: 2000
            geometry:
              type: boolean
              default: false
            gps_accuracy:
              type: integer
              default: 5
            interpolation_distance:
              type: integer
              default: 10
            max_route_distance_factor:
              type: integer
              default: 5
            max_route_time_factor:
              type: integer
              default: 5
            max_search_radius:
              type: integer
              default: 100
            route:
              type: boolean
              default: true
            search_radius:
              type: integer
              default: 50
            sigma_z:
              type: number
              format: double
              default: 4.07
            turn_penalty_factor:
              type: integer
              default: 0
        grid:
          type: object
          properties:
            cache_size:
              type: integer
              default: 100240
            size:
              type: integer
              default: 500
        logging:
          $ref: "#/components/schemas/logging"
        mode:
          type: string
          default: auto
        multimodal:
          type: object
          properties:
            turn_penalty_factor:
              type: integer
              default: 70
        pedestrian:
          type: object
          properties:
            search_radius:
              type: integer
              default: 50
            turn_penalty_factor:
              type: integer
              default: 100
        service:
          type: object
          properties:
            proxy:
              type: string
              default: ipc:///tmp/meili
        verbose:
          type: boolean
          default: false
    mjolnir:
      type: object
      properties:
        admin:
          type: string
          default: /custom_data/admins.sqlite
        data_processing:
          type: object
          properties:
            allow_alt_name:
              type: boolean
              default: false
            apply_country_overrides:
              type: boolean
              default: true
            infer_internal_intersections:
              type: boolean
              default: true
            infer_turn_channels:
              type: boolean
              default: true
            scan_tar:
              type: boolean
              default: false
            use_admin_db:
              type: boolean
              default: true
            use_direction_on_ways:
              type: boolean
              default: false
            use_rest_area:
              type: boolean
              default: false
            use_urban_tag:
              type: boolean
              default: false
        global_synchronized_cache:
          type: boolean
          default: false
        hierarchy:
          type: boolean
          default: true
        id_table_size:
          type: integer
          default: 1300000000
        import_bike_share_stations:
          type: boolean
          default: false
        include_bicycle:
          type: boolean
          default: true
        include_construction:
          type: boolean
          default: false
        include_driveways:
          type: boolean
          default: true
        include_driving:
          type: boolean
          default: true
        include_pedestrian:
          type: boolean
          default: true
        logging:
          $ref: "#/components/schemas/logging"
        lru_mem_cache_hard_control:
          type: boolean
          default: false
        max_cache_size:
          type: integer
          default: 1000000000
        max_concurrent_reader_users:
          type: integer
          default: 1
        reclassify_links:
          type: boolean
          default: true
        shortcuts:
          type: boolean
          default: true
        tile_dir:
          type: string
          default: ""
        tile_extract:
          type: string
          default: ""
        timezone:
          type: string
          default: timezones.sqlite
        traffic_extract:
          type: string
          default: ""
        transit_dir:
          type: string
          default: ""
        transit_feeds_dir:
          type: string
          default: ""
        use_lru_mem_cache:
          type: boolean
          default: false
        use_simple_mem_cache:
          type: boolean
          default: false
    odin:
      type: object
      properties:
        logging:
          $ref: "#/components/schemas/logging"
        markup_formatter:
          type: object
          properties:
            markup_enabled:
              type: boolean
              default: false
            phoneme_format:
              type: string
              default: <TEXTUAL_STRING> (<span class=<QUOTES>phoneme<QUOTES>>/<VERBAL_STRING>/</span>)
        service:
          type: object
          properties:
            proxy:
              type: string
              default: ipc:///tmp/odin
    service_limits:
      type: object
      properties:
        auto:
          type: object
          properties:
            max_distance:
              type: integer
              default: 5000000
            max_locations:
              type: integer
              default: 20
            max_matrix_distance:
              type: integer
              default: 400000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        bicycle:
          type: object
          properties:
            max_distance:
              type: integer
              default: 500000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 200000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        bikeshare:
          type: object
          properties:
            max_distance:
              type: integer
              default: 500000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 200000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        bus:
          type: object
          properties:
            max_distance:
              type: integer
              default: 5000000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 400000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        centroid:
          type: object
          properties:
            max_distance:
              type: integer
              default: 200000
            max_locations:
              type: integer
              default: 5
        isochrone:
          type: object
          properties:
            max_contours:
              type: integer
              default: 4
            max_distance:
              type: integer
              default: 25000
            max_distance_contour:
              type: integer
              default: 200
            max_locations:
              type: integer
              default: 1
            max_time_contour:
              type: integer
              default: 120
        max_alternates:
          type: integer
          default: 2
        max_exclude_locations:
          type: integer
          default: 50
        max_exclude_polygons_length:
          type: integer
          default: 10000
        max_radius:
          type: integer
          default: 200
        max_reachability:
          type: integer
          default: 100
        max_timedep_distance:
          type: integer
          default: 500000
        max_timedep_distance_matrix:
          type: integer
          default: 0
        motor_scooter:
          type: object
          properties:
            max_distance:
              type: integer
              default: 500000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 200000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        motorcycle:
          type: object
          properties:
            max_distance:
              type: integer
              default: 500000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 200000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        multimodal:
          type: object
          properties:
            max_distance:
              type: integer
              default: 500000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 0
            max_matrix_location_pairs:
              type: integer
              default: 0
        pedestrian:
          type: object
          properties:
            max_distance:
              type: integer
              default: 250000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 200000
            max_matrix_location_pairs:
              type: integer
              default: 2500
            max_transit_walking_distance:
              type: integer
              default: 10000
            min_transit_walking_distance:
              type: integer
              default: 1
        skadi:
          type: object
          properties:
            max_shape:
              type: integer
              default: 750000
            min_resample:
              type: integer
              default: 10
        status:
          type: object
          properties:
            allow_verbose:
              type: boolean
              default: false
        taxi:
          type: object
          properties:
            max_distance:
              type: integer
              default: 5000000
            max_locations:
              type: integer
              default: 20
            max_matrix_distance:
              type: integer
              default: 400000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        trace:
          type: object
          properties:
            max_alternates:
              type: integer
              default: 3
            max_alternates_shape:
              type: integer
              default: 100
            max_distance:
              type: integer
              default: 200000
            max_gps_accuracy:
              type: integer
              default: 100
            max_search_radius:
              type: integer
              default: 100
            max_shape:
              type: integer
              default: 16000
        transit:
          type: object
          properties:
            max_distance:
              type: integer
              default: 500000
            max_locations:
              type: integer
              default: 50
            max_matrix_distance:
              type: integer
              default: 200000
            max_matrix_location_pairs:
              type: integer
              default: 2500
        truck:
          type: object
          properties:
            max_distance:
              type: integer
              default: 5000000
            max_locations:
              type: integer
              default: 20
            max_matrix_distance:
              type: integer
              default: 400000
            max_matrix_location_pairs:
              type: integer
              default: 2500
    statsd:
      type: object
      properties:
        port:
          type: integer
          default: 8125
        prefix:
          type: string
          default: valhalla
    thor:
      type: object
      properties:
        clear_reserved_memory:
          type: boolean
          default: false
        extended_search:
          type: boolean
          default: false
        logging:
          type: object
          properties:
            color:
              type: boolean
              default: true
            file_name:
              type: string
              default: path_to_some_file.log
            long_request:
              type: integer
              default: 110
            type:
              type: string
              default: std_out
        max_reserved_labels_count:
          type: integer
          default: 1000000
        service:
          type: object
          properties:
            proxy:
              type: string
              default: ipc:///tmp/thor
        source_to_target_algorithm:
          type: string
          default: select_optimal
